title: Brian Vilnrotter | Incident response Analyst & Aspiring Data Scientist in Machine Learning
description: "Leveraging a decades worth of experience as an incident response analyst with a focus on transitioning into data science and machine learning."
baseurl: "/portfolio"
data_dir: _data
