name: Weekly Script Runner

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run udate_repos.py
              run: python scripts/update_repos.py

            - name: Run update_email_trends scripts
              env:
                NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
                DATABASE_ID: ${{ secrets.NOTION_EMAIL_TRENDS_DBID }}
              run: |
                python scripts/update_email_trends.py

            - name: Commit and push changes
              run: |
                git config --global user.name 'GitHub Actions'
                git config --global user.email 'actions@github.com'
                git add _data/repos.html
                git commit -m "Update repos.html"
                git push
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
